app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app
import datetime
from flask_login import UserMixin


from . import login_manager

from app import db


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String(64), unique=True, index=True)
    name = db.Column(db.String, nullable=True)
    age = db.Column(db.Integer, nullable=True)
    password_hash = db.Column(db.String(128))
    confirmed = db.Column(db.Boolean, default=False)
    is_administrator = db.Column(db.Boolean, default=False)
    location = db.Column(db.String(64))
    about_me = db.Column(db.Text())
    register_date = db.Column(db.DateTime(), default=datetime.datetime.utcnow)
    is_online = db.Column(db.Boolean, default=False)


    # Password setting
    @property
    def password(self):
        raise AttributeError("Password is not a readable field")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)


    # Age setting
    @property
    def user_age(self):
        return self.age
    
    @user_age.setter
    def user_age(self, year):
        curr_date = str(datetime.date.today()).split('-')
        self.age = int(curr_date[0]) - int(year)

    # user account confirmation
    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id})

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        db.session.commit()
        return True


@login_manager.user_loader
def loaduser(user_id):
    return User.query.get(int(user_id))

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_moment import Moment
from flask_mail import Mail
from flask_login import LoginManager
from config import config

mail = Mail()
db = SQLAlchemy()
moment = Moment()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    config[config_name].init_app(app)

    mail.init_app(app)
    db.init_app(app)
    moment.init_app(app)
    login_manager.init_app(app)

    #Attaching blue prints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix="/auth")

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, abort
from flask_login import login_required, current_user
from . import main
from ..models import User

@main.route('/')
def index():
    return render_template('main/index.html')

@main.route('/about')
def about():
    return render_template('main/about.html')

@main.route('/user/<username>')
def profile(username):
    user = User.query.filter_by(name=username).first()
    if not user:
        abort(404)
    return render_template('main/profile.html', user=user)

@main.route('/settings')
@login_required
def settings():
    user = User.query.filter_by(email=current_user.email).first()
    return render_template('main/information.html', user=user)

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width">
    <title>Chatty - {% block title %}{% endblock title %}</title>
    <!-- <link href="{{ url_for('static', filename='css/bootstrap/bootstrap.min.css') }}" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
</head>
<body>
    {% block nav %}
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg nav-custom navbar-light">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Chatty</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end mr-4" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                    </li>
                    {% if not current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link account-but" href="{{ url_for('auth.register') }}">Make Account</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.profile', username=current_user.name) }}">Account</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link account-but" href="#">Your Chat</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
    {% endblock nav %}
    
    <div class="container mt-2">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-success" role="alert">{{ message }}</div>
        {% endfor %}
    </div>
        
    {% block content %}{% endblock content %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    {{ moment.include_moment() }}
</body>
</html>

app/templates/main/404_error.html
{% extends "base.html" %}
{% block title %}Page Not Found{% endblock title %}

{% block content %}
    <div class="container-fluid">
        <h2>Error 404: This Page Does Not Exist :(</h2>
        <p>There are many other good pages that you can visit. You can visit our <a href="{{ url_for('main.index') }}">main</a> page</p>
    </div>
{% endblock content %}

app/templates/main/about.html
{% extends "base.html" %}
{% block title %}About{% endblock title %}

{% block content %}
<div class="container">
        <div class="text-justify mt-4">
            <h2>Reason Behind Chatty</h2>
            <hr>
            <p>Every skill based worker needs a portfolio that they can show off as to prove their skills. As a web development student, I have always worried about the outside market. I do not have a complete confidence in my skills and I do not know how much I know.</p>
            <p>Chatty will work as a proof for my skills and also as something that I can show off to other people. This is a time taking project but I have people who have been guiding me and supporting me. This is not just my hardwork. There is other people's support behind this project</p>
            <p>Chatty is a portfolio. This is in no way a commercial product on which I would want to earn on. This is a learning project that I will grow as time goes on. It will nourish as I learn more and more.</p>
        </div>
    <hr> 
    
    <div class="img-panel">
        <h2>Some Cool Pictures, Just for Fun</h2>
        <div class="row mt-4">
            <div class="col-md-4 mt-2">
                <img src="{{ url_for('static', filename='pic1.jpg') }}" class="img-fluid" alt="Intro Image">
            </div>

            <div class="col-md-4 mt-2">
                <img src="{{ url_for('static', filename='pic2.jpg') }}" class="img-fluid" alt="Intro Image">
            </div>

            <div class="col-md-4 mt-2">
                <img src="{{ url_for('static', filename='pic3.jpg') }}" class="img-fluid" alt="Intro Image">
            </div>
        </div>
    </div>

    <div class="about">
        <h2>About Me</h2>
        <p>Hello, my name is Saim Irfan and I am in a learning process. This is just a humble beginning. A very humble start</p>
        <h3>My Socials</h3>
        <ul class="list-unstyled social-links">
            <li><a href="https://github.com/Sammy275/" target="#">Github</a></li>
            <li><a href="https://www.facebook.com/saim.irfan.275/" target="#">Facebook</a></li>
        </ul>
    </div>
</div>
{% endblock content %}

app/templates/main/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock title %}

{% block content %}
<div class="container">
    <div class="row mt-4 intro">
        <div class="col-md-4 text-justify">
            <h2>About Chatty</h2>
            <hr>
            <p>Chatty is an online chatting application, it is simple is that. Make an account and find people based on your interest, location and so much more. Main goal of Chatty is that you have the best online interaction with people on the internet.</p>
        </div>

        <div class="col-md-8 text-md-center">
            <img src="{{ url_for('static', filename='intro.jpg') }}" class="ml-md-4 img-fluid" alt="Intro Image">
        </div>
    </div>
    <hr> 
    
</div>
{% endblock content %}

app/templates/main/information.html
{% extends "base.html" %}
{% block title %}Information{% endblock title %}
{% block nav %}{% endblock nav %}
{% block content %}

<div class="container-fluid">
    <div class="errors">
        {% for error in errors %}
        <div class="alert alert-danger" role="alert">{{ error }}</div>
        {% endfor %}
      </div> 

    <div class='banner'>
    <h5>Update your Account Details</h5>
    </div>

    <div class="row mt-2">
        <div style="background-color: #40c2ff; border-radius: 5px;" class="col-md-2 side-nav">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <h5 class="nav-link active">Side Navigation</h5>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{{ url_for('main.profile', username=user.name) }}">Your Account</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Log out</a>
                  </li>
            </ul>
        </div>
        <div class="col-md-9 mb-3">
            <form method="POST" action="{{ url_for('main.index') }}" class="info-form">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input name="username" type="text" class="form-control" id="username" value="{{ user.username }}">
                </div>

                <div class="form-group">
                    <label for="location">Location</label>
                    {% if user.location %}
                    <input name="location" type="text" class="form-control" id="username" value="{{ user.location }}">
                    {% else %}
                    <input name="location" type="text" class="form-control" id="username" value="" placeholder="Not given">
                    {% endif %}
                </div>
                    
                <div><label>Gender</label></div>
                <div class="form-check form-check-inline mb-1">
                    {% if user.gender == 0 %}
                    <input class="form-check-input" type="radio" name="gender" id="inlineRadio1" value="0" checked>
                    {% else %}
                    <input class="form-check-input" type="radio" name="gender" id="inlineRadio1" value="0">
                    {% endif %}
                    <label class="form-check-label" for="inlineRadio1">Male</label>
                </div>
                <div class="form-check form-check-inline">
                    {% if user.gender == 1 %}
                    <input class="form-check-input" type="radio" name="gender" id="inlineRadio2" value="1" checked>
                    {% else %}
                    <input class="form-check-input" type="radio" name="gender" id="inlineRadio2" value="1">
                    {% endif %}
                    <label class="form-check-label" for="inlineRadio2">Female</label>
                </div>
                <div class="form-check form-check-inline">
                    {% if user.gender == 2 %}
                    <input class="form-check-input" type="radio" name="gender" id="inlineRadio3" value="2" checked>
                    {% else %}
                    <input class="form-check-input" type="radio" name="gender" id="inlineRadio3" value="2">
                    {% endif %}
                    <label class="form-check-label" for="inlineRadio3">Other</label>
                </div>

                <div class="form-group">
                    <label for="age">Age</label>
                    {% if user.age %}
                    <input name="age" type="number" class="form-control" id="age" value="{{ user.age }}">
                    {% else %}
                    <input name="age" type="number" class="form-control" id="age" value="" placeholder="Not Given">
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="exampleFormControlTextarea1">More about yourself</label>
                    {% if user.additional_info %}
                    <textarea name="additional-info" class="form-control" id="exampleFormControlTextarea1" rows="3">{{ user.additional_info }}</textarea>
                    {% else %}
                    <textarea name="additional-info" class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Not Given"></textarea>
                    {% endif %}
                  </div>
                <button type="submit" class="btn account-but">Update Info</button>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

app/templates/main/profile.html
{% extends "base.html" %}
{% block title %}
    {{ user.name }}
{% endblock title %}
{% block content %}
<div class="container padding">
    <div>
        <div class="user-detail">
            {% if user == current_user %}
                <p class="mt-4 ml-4 d-inline"><a class="btn btn-danger" href="{{ url_for('auth.logout') }}">Log Out</a></p>
                <p class="mr-4 float-right"><a class="btn btn-primary" href="{{ url_for('main.settings') }}">Settings</a></p>
            {% endif %}

            <div class="usr-img text-center mt-5">
                <img src="{{ url_for('static', filename='pic1.jpg') }}" class="rounded-circle" alt="User Pic" height="250", width="250">
                {% if user.is_online %}
                    <p><div class="mr-2 online"></div>Online</p>
                {% else %}
                    <p><div class="mr-2 offline"></div>Offline</p>
                {% endif %}
            </div>
            <div class="username text-center mt-4">
                <h2>{{ user.name }}</h2>
            </div>

            <div class="additional-info text-center">
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
            </div>

            <div class="additional-text">
                <div class="additional-text-wrap">
                    <h6>Additional Information</h6>
                    <div class="detail mt-4 mb-4">
                        {% if user.location %}<p>From <a href="http://map.google.com/?q={{ user.location }}" target="_">{{ user.location }}</a></p>{% endif %}
                    </div>

                    <div class="detail mt-4 mb-4">
                        {% if user.age %}<p>{{ user.age }} years old</p>{% endif %}
                    </div>

                    <div class="detail mt-4 mb-4">
                        {% if user.register_date %}<p>Registered on {{ moment(user.register_date).format('LL') }}</p>{% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}